employee_system/urls.py
from django.conf.urls import url
from . import views


app_name = 'employees'

urlpatterns = [
    url(r'^$', views.Employees.as_view() , name='list-employees'),
    url(r'^create', views.CreateEmployee.as_view(), name='create-employee'),
    url(r'^show/(?P<pk>\d+)/$', views.EmployeeDetail.as_view(), name='show-employee'),
    url(r'^update/(?P<pk>\d+)/$', views.UpdateEmployee.as_view(), name='update-employee'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteEmployee.as_view(), name='delete-employee'),
    url(r'^export/csv/$' , views.ExportCSV.as_view(), name='export-csv'),
    url(r'^import/csv/$' , views.ImportCSV.as_view(), name='import-csv'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('employee_system.urls', namespace='employees')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee_system/models.py
import datetime
from django.db import models
from django.core.validators import RegexValidator, FileExtensionValidator
from django.core.exceptions import ValidationError
from django.conf import settings
from django.urls import reverse


def account_file_size(uploaded_file):
    max_size_in_mb = int(settings.ACCOUNT_MAX_FILE_SIZE_UPLOAD / (1024 * 1024))
    if uploaded_file.size > settings.ACCOUNT_MAX_FILE_SIZE_UPLOAD:
        raise ValidationError(_("File too large. Size should not exceed {} MiB.".format(str(max_size_in_mb))))


class Employee(models.Model):
    mobile_validator = RegexValidator(regex=r'^\d{6,20}$',
                                      message="Mobile Number length must be between 6 and 20 numbers")
    extension_error_message = "Allowed file types: pdf, jpg, jpeg, png"
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    TYPE_CHOICES = (
        ('P', 'Permenant'),
        ('T', 'Temporary')
    )
    # you can make employee_code unique , but for testing import/export purposing may cause conflicts
    employee_code = models.CharField(max_length=60, blank=True)
    first_name = models.CharField(max_length=50, null=False, blank=False)
    last_name = models.CharField(max_length=50, null=False, blank=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    birth_date = models.DateField(blank=False, null=False)
    # you can make email unique , but for testing import/export purposing may cause conflicts
    email = models.EmailField(blank=False, null=False)
    # you can make mobile unique , but for testing import/export purposing may cause conflicts
    mobile = models.CharField(max_length=50, blank=False, null=True, validators=[mobile_validator],
                              verbose_name='Mobile Number')
    hire_date = models.DateField(blank=False, null=False)
    employee_type = models.CharField(max_length=1, choices=TYPE_CHOICES, blank=False, null=False)
    photo = models.ImageField(blank=True, null=True, upload_to='employees_images', validators=[FileExtensionValidator(
        allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message=extension_error_message), account_file_size])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def account_file_size(cls, uploaded_file):
        max_size_in_mb = int(settings.ACCOUNT_MAX_FILE_SIZE_UPLOAD / (1024 * 1024))
        if uploaded_file.size > settings.ACCOUNT_MAX_FILE_SIZE_UPLOAD:
            raise ValidationError("File too large. Size should not exceed {} MiB.".format(str(max_size_in_mb)))
    
    def get_absolute_url(self):
        return reverse('employees:show-employee', args=[self.id])

    # for auto generating unique employee_code
    def save(self, *args, **kwargs):
        if not self.employee_code:
            self.employee_code = self.first_name[:2] + self.mobile[5:] + self.email[:5] + datetime.now().time[8:]
        return super().save()

    class Meta:
        verbose_name = 'employee'
        verbose_name_plural = "employees"
        ordering = ("-created_at",)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

employee_system/forms.py
from django import forms
from .models import Employee
from crispy_forms.helper import FormHelper

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['first_name','last_name','gender','birth_date','email','mobile','hire_date','employee_type','photo']

employee_system/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Employee
from django.urls import reverse_lazy , reverse
from django.views.generic.base import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import render
import csv , io



class Employees(ListView):
    model = Employee
    template_name = 'employee_system/list_employees.html'
    paginate_by = 20


class EmployeeDetail(DetailView):
    model = Employee
    template_name = 'employee_system/employee_details.html'


class CreateEmployee(SuccessMessageMixin, CreateView):
    model = Employee
    template_name = 'employee_system/employee_create.html'
    fields = ["first_name", "last_name", "employee_code", "gender", "birth_date", "email", "mobile", "hire_date",\
              "employee_type", "photo"]
    success_message = "Employee created successfully"


class UpdateEmployee(SuccessMessageMixin, UpdateView):
    model = Employee
    template_name = 'employee_system/employee_create.html'
    fields = ["first_name", "last_name", "employee_code", "gender", "birth_date", "email", "mobile", "hire_date",\
              "employee_type", "photo"]
    success_message = "Employee updated successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit'] = True
        return context


class DeleteEmployee(SuccessMessageMixin, DeleteView):
    model = Employee
    success_message = "Employee deleted successfully"
    success_url = reverse_lazy('employees:list-employees')
    template_name = 'employee_system/confirm_employee_deletion.html'


class ExportCSV(View):
    def get(self, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="employees.csv"'
        writer = csv.writer(response)
        writer.writerow(["employee_code", "first_name", "last_name", "gender", "birth_date", "email", "mobile", "hire_date",\
              "employee_type"])
        employees = Employee.objects.all()
        for employee in employees:
            writer.writerow([employee.employee_code, employee.first_name, employee.last_name, employee.gender, employee.birth_date, employee.email, employee.mobile, employee.hire_date,\
              employee.employee_type])
        messages.info(self.request, "Data Exported Successfully")
        return response


class ImportCSV(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'employee_system/import.html')
    
    def post(self, *args, **kwargs):
        paramFile = io.TextIOWrapper(self.request.FILES['employees'].file)
        all_employees = csv.DictReader(paramFile)
        list_of_dict = list(all_employees)
        objects_list = [
        Employee(
            first_name=row['first_name'],
            last_name=row['last_name'],
            employee_code=row['employee_code'],
            gender=row['gender'],
            birth_date=row['birth_date'],
            email=row['email'],
            mobile=row['mobile'],
            hire_date=row['hire_date'],
            employee_type=row['employee_type']
                )
            for row in list_of_dict
            ]
        try:
            Employee.objects.bulk_create(objects_list)
            messages.info(self.request, "Data Imported Successfully")
        except Exception as e:
            messages.info(self.request, "Something Went Wrong")
            return HttpResponseRedirect(reverse('employees:import-csv'))
        return HttpResponseRedirect(reverse('employees:list-employees'))

templates/employee_system/confirm_employee_deletion.html
{% extends 'layout.html' %}

{% block content %}
    <div class="text-center">
        <form method="post">
            {% csrf_token %}
            <p class="delete-msg">
            <img src="{{MEDIA_URL}}/icons/Sad.png" width="50px" height="50px">
            </p>
            <p class="delete-msg">
                Are you sure you want to delete <b>"{{ employee.first_name }}"</b> ?
            </p>
            <a href="{% url 'employees:list-employees' %}" class="btn btn-secondary">NO</a>
            <button class="btn btn-primary" type="submit">Yes</button>
        </form>
    </div>
{% endblock %}

templates/employee_system/employee_create.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h4 class="mb-4">
        {% if not edit %}
        <img src="{{MEDIA_URL}}/icons/Create.png">  Create Employee
        {% else %}
        <img src="{{MEDIA_URL}}/icons/Update.png">  Update Employee
        {% endif %}
    </h4>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="float-right">
            <a href="{% url 'employees:list-employees' %}" class="btn btn-secondary">Back</a>
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </form>
{% endblock %}

templates/employee_system/employee_details.html
{% extends 'layout.html' %}

{% block content %}
    <h4 class="mb-3"><img src="{{MEDIA_URL}}/icons/Notes.png">{{ employee.first_name }} {{ employee.last_name}}</h4>
    <table class="table table-striped details-table-text">
        <!--  employee_code,first_name, last_name, gender,birth_day,email,mobile,hire_date, emp_type, photo. -->
        <thead>
            <tr>
                <th>Employee Details</th>
                <th style="text-align: right">
                    <a class="icon-block" href="{% url 'employees:list-employees' %}"><img src="{{MEDIA_URL}}/icons/Back.png"></a>

                    <a class="icon-block" href="{% url 'employees:update-employee' employee.id %}"><img src="{{MEDIA_URL}}/icons/Modify.png"></a>

                    <a class="icon-block" href="{% url 'employees:delete-employee' employee.id %}"><img src="{{MEDIA_URL}}/icons/Delete.png"></a>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="col" class="details-main">ID</td><td scope="colgroup">{{ employee.id }}</td>
            </tr>
            <tr>
                <td scope="col">First Name</td><td scope="col">{{ employee.first_name }}</td>
            </tr>
            <tr>
                <td scope="col">Last Name</td><td scope="col">{{ employee.last_name }}</td>
            </tr>
            <tr>
                <td scope="col">Code</td><td scope="col">{{ employee.employee_code }}</td>
            </tr>
            <tr>
                <td scope="col">Gender</td>
                <td scope="col">
                    {% if employee.gender == 'M'%}
                        Male
                    {% else %}
                        Female
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td scope="col">Birth Day</td><td scope="col">{{ employee.birth_date }}</td>
            </tr>
            <tr>
                <td scope="col">Email</td><td scope="col">{{ employee.email }}</td>
            </tr>
            <tr>
                <td scope="col">Mobile</td><td scope="col">{{ employee.mobile }}</td>
            </tr>
            <tr>
                <td scope="col">Hire Date</td><td scope="col">{{ employee.hire_date }}</td>
            </tr>
            <tr>
                <td scope="col">Type</td>
                <td scope="col">
                    {% if employee.employee_type == 'P'%}
                        Permanent
                    {% else %}
                        Temporary
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td scope="col">Photo</td><td scope="col">
                    {% if employee.photo %}
                        <img height="100" width="100" src="{{ employee.photo.url }}">
                    {% elif employee.gender == 'M' %}
                        <img height="100" width="100" src="{{ MEDIA_URL }}default/male.jpg">
                    {% else %}
                        <img height="100" width="100" src="{{ MEDIA_URL }}default/female.jpg">
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
    
{% endblock  %}

templates/employee_system/import.html
{% extends 'layout.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input required type="file" name="employees">
    <button type="submit">Upload</button>
  </form>
{% endblock %}

templates/employee_system/list_employees.html
{% extends 'layout.html' %}

{% block content %}
    {% if object_list %}
        <table class="table table-striped list-table-text">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Code</th>
                <th scope="col">Gender</th>
                <th scope="col">Birth Day</th>
                <th scope="col">Email</th>
                <th scope="col">Mobile</th>
                <th scope="col">Hire Date</th>
                <th scope="col">Type</th>
                <th scope="col">Show</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
                <th scope="col">
                    Photo
                </th>
                </tr>
            </thead>
            <tbody>
            {% for employee in object_list %}
                <tr onmouseenter="showImage({{ employee.id }})" onmouseleave="hideImage({{ employee.id }})">
                <td scope="col">{{ employee.id }}</td>
                <td scope="col">{{ employee.first_name }}</td>
                <td scope="col">{{ employee.last_name }}</td>
                <td scope="col">{{ employee.employee_code }}</td>
                {% if employee.gender == 'M'%}
                <td scope="col"><img src="{{MEDIA_URL}}/icons/Male.png"></td>
                {% else %}
                <td scope="col"><img src="{{MEDIA_URL}}/icons/Female.png"></td>
                {% endif %}
                <td scope="col">{{ employee.birth_date }}</td>
                <td scope="col">{{ employee.email }}</td>
                <td scope="col">{{ employee.mobile }}</td>
                <td scope="col">{{ employee.hire_date }}</td>
                {% if employee.employee_type == 'P'%}
                <td scope="col">Permanent</td>
                {% else %}
                <td scope="col">Temporary</td>
                {% endif %}
                <td scope="col">
                    <a href="{% url 'employees:show-employee' employee.id %}"><img src="{{MEDIA_URL}}/icons/View.png"></a>
                </td>
                <td scope="col">
                    <a href="{% url 'employees:update-employee' employee.id %}"><img src="{{MEDIA_URL}}/icons/Modify.png"></a>
                </td>
                <td scope="col">
                    <a href="{% url 'employees:delete-employee' employee.id %}"><img src="{{MEDIA_URL}}/icons/Delete.png"></a>
                </td>
                <td scope="col" id="td-{{ employee.id }}">
                    {% if employee.photo %}
                    <img class="employee-img" id="{{ employee.id }}" src="{{ employee.photo.url }}">
                    {% elif employee.gender == 'M'%}
                    <img class="employee-img" id="{{ employee.id }}" src="{{ MEDIA_URL }}default/male.jpg">
                    {% else %}
                    <img class="employee-img" id="{{ employee.id }}" src="{{ MEDIA_URL }}default/female.jpg">
                    {% endif %}
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="empty-languages">No Employee Info in Database</div>
    {% endif %}
    {% if page_obj.has_previous or page_obj.has_next %}
        <nav class="mt-4 d-flex justify-content-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item disabled"><a class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock  %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}EMS{% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/ico/database.ico' %}">
    <script>
        function showImage(id) {
            //document.getElementById("td-"+id).style.visibility = "visible";
            document.getElementById(id).style.visibility = "visible";
        }
        function hideImage(id) {
            //document.getElementById("td-"+id).style.visibility = "hidden";
            document.getElementById(id).style.visibility = "hidden";
        }
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
            <a class="navbar-brand" href="{% url 'employees:list-employees' %}"><img src="{% static '/images/ico/boss.ico' %}"> Employees Management System</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'employees:export-csv' %}"><img src="{% static '/images/png/Fall.png' %}">Export CSV</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'employees:import-csv' %}"><img src="{% static '/images/png/Raise.png' %}">Import CSV</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'employees:create-employee' %}"><img src="{% static '/images/png/Add.png' %}"> Add</a>
                    </li>
                </ul>
            </div>
    </nav>

    <main class="container-fluid main-content">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
          {% endif %}
        {% block content %}
        {% endblock  %}
    </main>
    <footer class="footer">
        <div class="container">
            Employees Management System <a href="https://www.linkedin.com/in/al-motaz-hejazy/">Motaz Hejaze</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>